import { FaFire } from "react-icons/fa";

export const originals = [
  {
    id: 1,
    name: "Crash",
    creator: "Roobet",
    img: "/games/img2.png",
    exclusive: true,
    new: false,
    link: "/",
  },
  {
    id: 2,
    name: "Crash",
    creator: "Roobet",
    img: "/games/img2.png",
    exclusive: false,
    new: true,
    link: "/",
  },
  {
    id: 3,
    name: "Crash",
    creator: "Roobet",
    img: "/games/test.jpeg",
    exclusive: true,
    new: false,
    link: "/",
  },
  {
    id: 4,
    name: "Crash",
    creator: "Roobet",
    img: "/games/img2.png",
    exclusive: false,
    new: false,
    link: "/",
  },
  {
    id: 5,
    name: "Crash",
    creator: "Roobet",
    img: "/games/img2.png",
    exclusive: false,
    new: false,
    link: "/",
  },
  {
    id: 6,
    name: "Crash",
    creator: "Roobet",
    img: "/games/img2.png",
    exclusive: false,
    new: false,
    link: "/",
  },
  {
    id: 7,
    name: "Crash",
    creator: "Roobet",
    img: "/games/img2.png",
    exclusive: false,
    new: false,
    link: "/",
  },
  {
    id: 8,
    name: "Crash",
    creator: "Roobet",
    img: "/games/img2.png",
    exclusive: false,
    new: false,
    link: "/",
  },
  {
    id: 9,
    name: "Crash",
    creator: "Roobet",
    img: "/games/img2.png",
    exclusive: false,
    new: false,
    link: "/",
  },
  {
    id: 10,
    name: "Crash",
    creator: "Roobet",
    img: "/games/img2.png",
    exclusive: false,
    new: false,
    link: "/",
  },
];

export const wins = [
  {
    id: 1,
    gameImg: "/games/img2.png",
    game: "Plinko",
    username: "Yash",
    time: "02:30 PM",
    wager: "$100.24",
    multiplier: "2.4x",
    payout: "$470.00",
  },
  {
    id: 2,
    gameImg: "/games/img2.png",
    game: "Crash",
    username: "Alice",
    time: "03:15 PM",
    wager: "$150.00",
    multiplier: "3.0x",
    payout: "$450.00",
  },
  {
    id: 3,
    gameImg: "/games/img2.png",
    game: "Roulette",
    username: "Mike",
    time: "04:10 PM",
    wager: "$75.50",
    multiplier: "1.8x",
    payout: "$135.90",
  },
  {
    id: 4,
    gameImg: "/games/img2.png",
    game: "Blackjack",
    username: "Emma",
    time: "05:00 PM",
    wager: "$200.00",
    multiplier: "2.0x",
    payout: "$400.00",
  },
  {
    id: 5,
    gameImg: "/games/img2.png",
    game: "Slots",
    username: "Sophia",
    time: "06:45 PM",
    wager: "$50.75",
    multiplier: "5.5x",
    payout: "$278.13",
  },
  {
    id: 6,
    gameImg: "/games/img2.png",
    game: "Baccarat",
    username: "Liam",
    time: "07:30 PM",
    wager: "$125.00",
    multiplier: "3.2x",
    payout: "$400.00",
  },
  {
    id: 7,
    gameImg: "/games/img2.png",
    game: "Keno",
    username: "Noah",
    time: "08:15 PM",
    wager: "$90.00",
    multiplier: "4.0x",
    payout: "$360.00",
  },
  {
    id: 8,
    gameImg: "/games/img2.png",
    game: "Sic Bo",
    username: "Olivia",
    time: "09:00 PM",
    wager: "$30.50",
    multiplier: "6.0x",
    payout: "$183.00",
  },
  {
    id: 9,
    gameImg: "/games/img2.png",
    game: "Craps",
    username: "Isabella",
    time: "10:30 PM",
    wager: "$60.00",
    multiplier: "2.5x",
    payout: "$150.00",
  },
  {
    id: 10,
    gameImg: "/games/img2.png",
    game: "Video Poker",
    username: "Mason",
    time: "11:15 PM",
    wager: "$80.00",
    multiplier: "3.5x",
    payout: "$280.00",
  },
  {
    id: 11,
    gameImg: "/games/img2.png",
    game: "Texas Hold'em",
    username: "Ava",
    time: "12:00 AM",
    wager: "$100.00",
    multiplier: "4.5x",
    payout: "$450.00",
  },
  {
    id: 12,
    gameImg: "/games/img2.png",
    game: "Bingo",
    username: "Lucas",
    time: "01:30 AM",
    wager: "$40.00",
    multiplier: "1.5x",
    payout: "$60.00",
  },
  {
    id: 13,
    gameImg: "/games/img2.png",
    game: "War",
    username: "Charlotte",
    time: "02:45 AM",
    wager: "$70.00",
    multiplier: "2.2x",
    payout: "$154.00",
  },
  {
    id: 14,
    gameImg: "/games/img2.png",
    game: "Horse Racing",
    username: "Ethan",
    time: "03:50 AM",
    wager: "$250.00",
    multiplier: "1.9x",
    payout: "$475.00",
  },
  {
    id: 15,
    gameImg: "/games/img2.png",
    game: "Fantasy Sports",
    username: "Mia",
    time: "04:30 AM",
    wager: "$55.00",
    multiplier: "3.0x",
    payout: "$165.00",
  },
  {
    id: 16,
    gameImg: "/games/img2.png",
    game: "Fantasy Sports",
    username: "Mia",
    time: "04:30 AM",
    wager: "$55.00",
    multiplier: "3.0x",
    payout: "$165.00",
  },
  {
    id: 17,
    gameImg: "/games/img2.png",
    game: "Fantasy Sports",
    username: "Mia",
    time: "04:30 AM",
    wager: "$55.00",
    multiplier: "3.0x",
    payout: "$165.00",
  },
  {
    id: 18,
    gameImg: "/games/img2.png",
    game: "Fantasy Sports",
    username: "Mia",
    time: "04:30 AM",
    wager: "$55.00",
    multiplier: "3.0x",
    payout: "$165.00",
  },
  {
    id: 19,
    gameImg: "/games/img2.png",
    game: "Fantasy Sports",
    username: "Mia",
    time: "04:30 AM",
    wager: "$55.00",
    multiplier: "3.0x",
    payout: "$165.00",
  },
  {
    id: 20,
    gameImg: "/games/img2.png",
    game: "Fantasy Sports",
    username: "Mia",
    time: "04:30 AM",
    wager: "$55.00",
    multiplier: "3.0x",
    payout: "$165.00",
  },
  {
    id: 21,
    gameImg: "/games/img2.png",
    game: "Fantasy Sports",
    username: "Mia",
    time: "04:30 AM",
    wager: "$55.00",
    multiplier: "3.0x",
    payout: "$165.00",
  },
  {
    id: 22,
    gameImg: "/games/img2.png",
    game: "Fantasy Sports",
    username: "Mia",
    time: "04:30 AM",
    wager: "$55.00",
    multiplier: "3.0x",
    payout: "$165.00",
  },
  {
    id: 23,
    gameImg: "/games/img2.png",
    game: "Fantasy Sports",
    username: "Mia",
    time: "04:30 AM",
    wager: "$55.00",
    multiplier: "3.0x",
    payout: "$165.00",
  },
  {
    id: 24,
    gameImg: "/games/img2.png",
    game: "Fantasy Sports",
    username: "Mia",
    time: "04:30 AM",
    wager: "$55.00",
    multiplier: "3.0x",
    payout: "$165.00",
  },
  {
    id: 25,
    gameImg: "/games/img2.png",
    game: "Fantasy Sports",
    username: "Mia",
    time: "04:30 AM",
    wager: "$55.00",
    multiplier: "3.0x",
    payout: "$165.00",
  },
  {
    id: 26,
    gameImg: "/games/img2.png",
    game: "Fantasy Sports",
    username: "Mia",
    time: "04:30 AM",
    wager: "$55.00",
    multiplier: "3.0x",
    payout: "$165.00",
  },
];

export const casino = [
  { id: 1, name: "Roobet Games", icon: FaFire },
  { id: 2, name: "Popular", icon: FaFire },
  { id: 3, name: "New Games", icon: FaFire },
  { id: 4, name: "Slots", icon: FaFire },
  { id: 5, name: "Bonus Buys", icon: FaFire },
  { id: 6, name: "Live Casino", icon: FaFire },
  { id: 7, name: "Game Shows", icon: FaFire },
  { id: 8, name: "Roulette", icon: FaFire },
  { id: 9, name: "Blackjack", icon: FaFire },
  { id: 10, name: "Baccarat", icon: FaFire },
];

export const sports = [
  { id: 1, name: "Soccer", icon: FaFire },
  { id: 2, name: "Basketball", icon: FaFire },
  { id: 3, name: "American Football", icon: FaFire },
  { id: 4, name: "Tennis", icon: FaFire },
  { id: 5, name: "Counter-Strike", icon: FaFire },
  { id: 6, name: "FIFA", icon: FaFire },
  { id: 7, name: "Baseball", icon: FaFire },
  { id: 8, name: "Ice-Hockey", icon: FaFire },
  { id: 9, name: "MMA", icon: FaFire },
  { id: 10, name: "Table Tennis", icon: FaFire },
  { id: 11, name: "Horse Racing", icon: FaFire },
];
