[[redirects]]
  from = "/game"
  to = "/index.html?redirect=game"
  status = 200

[[redirects]]
  from = "/game/wheel"
  to = "/index.html?redirect=game/wheel"
  status = 200

[[redirects]]
  from = "/game/diamond"
  to = "/index.html?redirect=game/diamond"
  status = 200

[[redirects]]
  from = "/game/mines"
  to = "/index.html?redirect=game/mines"
  status = 200

[[redirects]]
  from = "/game/balloon"
  to = "/index.html?redirect=game/balloon"
  status = 200

[[redirects]]
  from = "/game/crash"
  to = "/index.html?redirect=game/crash"
  status = 200

[[redirects]]
  from = "/game/dice"
  to = "/index.html?redirect=game/dice"
  status = 200

[[redirects]]
  from = "/game/limbo"
  to = "/index.html?redirect=game/limbo"
  status = 200

[[redirects]]
  from = "/game/keno"
  to = "/index.html?redirect=game/keno"
  status = 200

[[redirects]]
  from = "/game/plinko"
  to = "/index.html?redirect=game/plinko"
  status = 200

[[redirects]]
  from = "/game/cards"
  to = "/index.html?redirect=game/cards"
  status = 200

[[redirects]]
  from = "/game/baccarat"
  to = "/index.html?redirect=game/baccarat"
  status = 200

[[redirects]]
  from = "/game/blackjack"
  to = "/index.html?redirect=game/blackjack"
  status = 200

[[redirects]]
  from = "/game/hilo"
  to = "/index.html?redirect=game/hilo"
  status = 200

[[redirects]]
  from = "/sports"
  to = "/index.html?redirect=sports"
  status = 200

[[redirects]]
  from = "/sports"
  to = "/index.html?redirect=sports"
  status = 200

[[redirects]]
  from = "/sports/cricket"
  to = "/index.html?redirect=sports/cricket"
  status = 200

[[redirects]]
  from = "/sports/cricket/bet"
  to = "/index.html?redirect=sports/cricket/bet"
  status = 200

[[redirects]]
  from = "/sports/football"
  to = "/index.html?redirect=sports/football"
  status = 200

[[redirects]]
  from = "/sports/football/bet"
  to = "/index.html?redirect=sports/football/bet"
  status = 200

